-- Baseline: the schema Hibernate generated before Flyway was introduced (Spring Boot 3.5, PostgreSQL 17).
-- Existing databases are baselined at this version; fresh databases run it.


create table applications (
    application_date date not null,
    salary_range_max integer,
    salary_range_min integer,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) not null,
    notes varchar(2000),
    company varchar(255) not null,
    job_url varchar(255),
    location varchar(255),
    requisition_id varchar(255),
    resume_variant varchar(255) not null check (resume_variant in ('VARIANT_A_DEFENSE','VARIANT_B_COMMERCIAL','VARIANT_C_CACI_SPECIFIC')),
    role varchar(255) not null,
    source varchar(255) not null check (source in ('COLD','REFERRAL','RECRUITER','EVENT','INTERNAL')),
    status varchar(255) not null check (status in ('APPLIED','SCREENING','INTERVIEWING','OFFER','REJECTED','WITHDRAWN','GHOSTED')),
    primary key (id)
);

create table certifications (
    exam_date date,
    hours_studied integer,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) not null,
    name varchar(255) not null,
    notes TEXT,
    status varchar(255) not null check (status in ('PLANNING','STUDYING','SCHEDULED','PASSED','FAILED')),
    vendor varchar(255) not null,
    primary key (id)
);

create table documents (
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) not null,
    notes TEXT,
    path varchar(255) not null,
    title varchar(255) not null,
    type varchar(255) not null check (type in ('RESUME','PLAN','GUIDE','SPEC','OTHER')),
    version varchar(255),
    primary key (id)
);

create table fitness_sessions (
    duration_minutes integer not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    session_date timestamp(6) not null,
    updated_at timestamp(6) not null,
    notes varchar(2000),
    workout_type varchar(255) not null check (workout_type in ('WORKOUT_A','WORKOUT_B','WALK','OTHER')),
    primary key (id)
);

create table plan_events (
    created_at timestamp(6) not null,
    event_time timestamp(6) not null,
    id bigint generated by default as identity,
    plan_item_id bigint not null,
    notes varchar(2000),
    from_status varchar(255) check (from_status in ('PLANNED','IN_PROGRESS','DONE','CANCELED','DEFERRED')),
    to_status varchar(255) not null check (to_status in ('PLANNED','IN_PROGRESS','DONE','CANCELED','DEFERRED')),
    primary key (id)
);

create table plan_items (
    target_date date,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    reference_entity_id bigint,
    updated_at timestamp(6) not null,
    notes varchar(2000),
    intent varchar(255) not null check (intent in ('STUDY','EXERCISE','APPLY','READ','WRITE','OTHER')),
    reference_entity_type varchar(255) check (reference_entity_type in ('CERTIFICATION','APPLICATION','DOCUMENT','STUDY_SESSION','FITNESS_SESSION','PLAN_ITEM')),
    status varchar(255) not null check (status in ('PLANNED','IN_PROGRESS','DONE','CANCELED','DEFERRED')),
    title varchar(255) not null,
    primary key (id)
);

create table study_sessions (
    duration_minutes integer not null,
    certification_id bigint,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    session_date timestamp(6) not null,
    updated_at timestamp(6) not null,
    notes varchar(2000),
    primary key (id)
);
