-- Reality can point back at intention: sessions logged from a plan item keep its id.
alter table study_sessions add column plan_item_id bigint;
alter table fitness_sessions add column plan_item_id bigint;

-- Routines that generate plan items on chosen weekdays.
create table recurring_plans (
    id bigint generated by default as identity,
    title varchar(255) not null,
    intent varchar(255) not null check (intent in ('STUDY','EXERCISE','APPLY','READ','WRITE','OTHER')),
    days varchar(255) not null,
    reference_entity_type varchar(255) check (reference_entity_type in ('CERTIFICATION','APPLICATION','DOCUMENT','STUDY_SESSION','FITNESS_SESSION','PLAN_ITEM')),
    reference_entity_id bigint,
    notes varchar(2000),
    active boolean not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    primary key (id)
);

alter table plan_items add column recurring_plan_id bigint;
create index idx_plan_items_recurring on plan_items (recurring_plan_id, target_date);

-- Change sets waiting for review in the app (posted by the MCP server or other agents).
create table proposals (
    id bigint generated by default as identity,
    source varchar(255) not null,
    summary varchar(2000),
    changes_json text not null,
    status varchar(255) not null check (status in ('PENDING','APPLIED','DISMISSED')),
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    primary key (id)
);
create index idx_proposals_status on proposals (status, created_at);
